POST http://localhost:5270/champions
Content-Type: application/json

{
	"name": "Test",
	"cost": {
		"BlueEssence": 1800,
		"RiotPoints": 200
	}
}

###

GET https://localhost:7193/Champions/aea5a030-e434-414c-a197-2b58edffbd1f