@id=4db062b6-c375-43f9-9ec1-e8963b08533d

PUT http://localhost:5270/champions/{{id}}
Content-Type: application/json

{
	"name": "Kha'Zix 2.0",
	"cost": {
		"BlueEssence": 1800,
		"RiotPoints": 200
	}
}